# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-ad-manager:
    defaults:
      run:
        working-directory: ./ad-manager
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      # set up python 
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: | 
          pip install -r requirements.txt

      - name: packaging
        run: pyinstaller submit.py --onefile --add-binary ./driver/chromedriver-85.exe

      - name: archive exe file
        uses: actions/upload-artifact@v2
        with:
          name: submit.exe
          path: D:\a\auto-submit\auto-submit\ad-manager\dist\submit.exe
